Sync scrollbar on coc#util#float_scroll_i
neoclide/coc.nvim pull request #2532
Opened 2020-10-28 02:56 UTC by oblitum

Solves #2521

2020-10-28 06:51 UTC, chemzqm commented
Please add documentation.

2020-10-28 10:35 UTC, chemzqm commented
You can use `redraw` instead of timer.

2020-10-28 15:48 UTC, oblitum commented
Hi @chemzqm, I see there's lots of refactoring/deprecation on util.vim. So I think it's best to also move this function to float.vim? Given that it's pretty recent and not many people are depending on it, what you think of simply moving it there without "deprecating" the not-very-old function?

So this is a list of questions to answer:

- Can I just move this function to float.vim without deprecation notice?
- Can I rename this function completely? `float_scroll_i` isn't a good name for functions in `coc#float`, should it be named `coc#float#something`, do you have an idea for a  name? Maybe `coc#float#nvim_scroll`?
- I've used the timer trick because calling it directly generated error E523 and the timer avoids that, it's not about a screen refresh problem. Does `redraw` fix that? Not sure how to use it and whether that suggestion is to fix that problem.
- I will add docs about the function to doc.txt and to this PR commit message. Is that sufficient?

To conclude, I think it's still fine for this function to exist in some form, without deprecation, because there's no other way to scroll in visual mode (I plan to add that to the docs).

2020-10-28 17:02 UTC, chemzqm commented
It's possible to cancel selection and make coc.nvim select the region again.

2020-10-28 17:12 UTC, oblitum commented
Okay. I'll rewrite this PR anyway. I won't cover rewriting it by a re-selectio mechanism. Sounds interesting though, but may present flicker side-effect.

2020-10-29 03:51 UTC, chemzqm requested changes

2020-10-29 03:51 UTC, chemzqm commented on autoload/coc/float.vim
> +  let scrolloff = &scrolloff*2 < win_height ? &scrolloff : 0
Should use `getwinvar()` for scrolloff option here

2020-10-29 04:53 UTC, oblitum commented on autoload/coc/float.vim
> +  let scrolloff = &scrolloff*2 < win_height ? &scrolloff : 0
Okay. I'll add but I don't exactly agree because it's a global option, so there's solely one value for it, always present.

2020-10-29 04:57 UTC, chemzqm commented on autoload/coc/float.vim
> +  let scrolloff = &scrolloff*2 < win_height ? &scrolloff : 0
It's not on latest vim and neovim 0.5.0, coc.nvim change it to 0 on neovim 0.5.0

2020-10-29 05:01 UTC, oblitum commented on autoload/coc/float.vim
> +  let scrolloff = &scrolloff*2 < win_height ? &scrolloff : 0
Oh, okay, so this option does not exist anymore?? Do you know if it's being simply removed or an alternative is being offered? Because it was somewhat useful for people.

2020-10-29 05:25 UTC, oblitum commented on autoload/coc/float.vim
> +  let scrolloff = &scrolloff*2 < win_height ? &scrolloff : 0
Ah okay, I interpreted it badly, it's has become window local.

2020-10-29 06:13 UTC, merged