Columnar alignment of CocLists
neoclide/coc.nvim pull request #2640
Opened 2020-11-22 23:15 UTC by elkowar

This PR implements improved formatting options for CocList. Specifically, it adds the option to align the content of CocLists in columns, making it look much nicer.

Additionally, it adds a couple options to configure what is shown in the diagnostics output, making the filepath and diagnostic-code configurable. 

## Example images

### Outline view
![coc-showcase-1](https://user-images.githubusercontent.com/5300871/99919904-89db8300-2d20-11eb-88c0-d695439cd5d7.png)

### lists list
![coc-showcase-2](https://user-images.githubusercontent.com/5300871/99919905-8c3ddd00-2d20-11eb-8cde-1df4c6b6d592.png)

### Commands list
![coc-showcase-3](https://user-images.githubusercontent.com/5300871/99919916-a1b30700-2d20-11eb-991c-16fb0eebfb86.png)

### Diagnostics list with minimal configuration
Here the only the filename is shown, and the error code is completely hidden
![coc-showcase-4](https://user-images.githubusercontent.com/5300871/99919941-b98a8b00-2d20-11eb-81be-2c1755d84100.png)

### Diagnostics list with more data
Here a shortened version of the path is shown
![coc-showcase-5](https://user-images.githubusercontent.com/5300871/99919952-ceffb500-2d20-11eb-8eb8-c74492563f3a.png)

2020-11-23 03:31 UTC, chemzqm requested changes

2020-11-23 03:31 UTC, chemzqm commented on src/list/formatting.ts
> +    const segments = path.split("/")
Use `path.sep` instead.

2020-11-23 03:31 UTC, chemzqm commented on src/list/formatting.ts
> +    return [...shortenedInit, segments[segments.length - 1]].join("/")
Use `path.sep` instead.

2020-11-23 11:04 UTC, exorcist-git approved these changes
Seems legit.

2020-11-24 04:11 UTC, chemzqm requested changes

2020-11-24 04:11 UTC, chemzqm commented on data/schema.json
> +    "diagnostic.listIncludeCode": {
Please change `diagnostic.listIncludeCode` to `list.source.diagnostics.includeCode` and `diagnostic.listFormatPath` to `list.source.diagnostics.pathFormat` since they only affect diagnostic list.

2020-11-25 04:13 UTC, chemzqm approved these changes

2020-11-25 07:00 UTC, merged