feat(markdown): ignore image in markdown doc
neoclide/coc.nvim pull request #3100
Opened 2021-05-20 06:41 UTC by fannheyward

ignore `![alt](href)` in markdown text.

2021-05-20 06:46 UTC, chemzqm commented
Why exclude image links?

2021-05-20 06:56 UTC, fannheyward commented
<img width="776" alt="截屏2021-05-20 下午2 55 57" src="https://user-images.githubusercontent.com/345274/118933180-7cbfe980-b97b-11eb-9b46-191c1aab7700.png">

2021-05-20 06:57 UTC, fannheyward commented
Maybe we should ignore base64 image url only?

2021-05-20 08:43 UTC, chemzqm commented
We need to use option to trim image url since the terminal could render image and vim may provide api to render image.

2021-05-20 08:45 UTC, chemzqm requested changes

2021-05-20 08:45 UTC, chemzqm commented on src/markdown/index.ts
> +    if (/!\[.*?\]\(.*?\)/.test(line)) {
The image may follow by other text, this would ignore them as well.

2021-05-20 08:45 UTC, chemzqm commented on src/markdown/index.ts
> +    if (/!\[.*?\]\(.*?\)/.test(line)) {
It should only be ignored when whole line is images, replace images with empty string for other cases.

2021-05-20 10:42 UTC, fannheyward commented on src/markdown/index.ts
> +    if (/!\[.*?\]\(.*?\)/.test(line)) {
Replace image pattern to empty string and check  line.length, only ignore whole line empty.

2021-05-27 02:59 UTC, gk488 approved these changes

2021-06-05 03:59 UTC, merged