Allow whitespace as trigger characters
neoclide/coc.nvim pull request #3227
Opened 2021-07-21 04:33 UTC by NoahTheDuke

[coc-clojure](https://github.com/noahtheduke/coc-clojure) uses spaces.

2021-07-21 07:42 UTC, chemzqm requested changes

2021-07-21 07:42 UTC, chemzqm commented on src/provider/signatureManager.ts
> -    let characters = triggerCharacters.reduce((p, c) => p.concat(c.split(/\s*/g)), [] as string[])
Change this line to
```
let characters = triggerCharacters.reduce((p, c) => p.concat(c.startsWith(' ') ? [' ']: c.split(/\s*/g)), [] as string[])
```

2021-07-21 13:52 UTC, NoahTheDuke commented on src/provider/signatureManager.ts
> -    let characters = triggerCharacters.reduce((p, c) => p.concat(c.split(/\s*/g)), [] as string[])
The goal was to allow for characters other than <space>, such as <newline>. The spec isn't clear either way. What do you think?

2021-07-21 15:32 UTC, chemzqm commented on src/provider/signatureManager.ts
> -    let characters = triggerCharacters.reduce((p, c) => p.concat(c.split(/\s*/g)), [] as string[])
Use

``` ts
let characters = triggerCharacters.reduce((p, c) => p.concat(c.length == 1 ? c : c.split(/\s*/g)), [] as string[])
```

2021-07-21 15:32 UTC, NoahTheDuke commented on src/provider/signatureManager.ts
> -    let characters = triggerCharacters.reduce((p, c) => p.concat(c.split(/\s*/g)), [] as string[])
Cool, thank you.

2021-07-21 15:43 UTC, chemzqm requested changes

2021-07-21 15:43 UTC, chemzqm commented on src/provider/signatureManager.ts
> +    let characters = triggerCharacters.reduce((p, c) => p.concat(c.length == 1 ? c : c.split(/\s*/g)), [] as string[])
Should be `p.concat(c.length == 1 ? [c]`

2021-07-21 15:44 UTC, NoahTheDuke commented on src/provider/signatureManager.ts
> +    let characters = triggerCharacters.reduce((p, c) => p.concat(c.length == 1 ? c : c.split(/\s*/g)), [] as string[])
```suggestion
    let characters = triggerCharacters.reduce((p, c) => p.concat(c.length == 1 ? [c] : c.split(/\s*/g)), [] as string[])
```

2021-07-21 15:45 UTC, NoahTheDuke commented on src/provider/signatureManager.ts
> +    let characters = triggerCharacters.reduce((p, c) => p.concat(c.length == 1 ? c : c.split(/\s*/g)), [] as string[])
Oops, missed your edit. Thanks so much.

2021-07-21 17:03 UTC, merged

2021-08-18 18:19 UTC, oblitum commented
@NoahTheDuke Hi. I'm just trying out Clojure for the first time (but I'm a long time coc.nvim user). Does your PR still work in latest coc.nvim? I'm using your coc-clojure extension and this code won't trigger signature help (I was unable to get signatureHelp to be triggered, not sure whether I need to write some special Clojure code declaration that would cause signatures to show up):

```clojure
(defn greet  [name]  (str "Hello, " name) )

(greet <space here triggers nothing>
```

2021-08-24 02:54 UTC, oblitum commented
@NoahTheDuke ping?

2021-08-28 14:29 UTC, oblitum commented
I'm able to get signatureHelp from clojure-lsp only through manual `CocActionAsync('showSignatureHelp')` from insert mode:

![gif-2021-08-28-112332](https://user-images.githubusercontent.com/1269815/131221250-fc3a672b-06ae-4a33-8e25-625a421b096c.gif)

Automatically after whitespace nothing comes up:
![gif-2021-08-28-112540](https://user-images.githubusercontent.com/1269815/131221249-f2c7ec03-6c47-4262-96fd-87a42a32f8d1.gif)

2021-11-16 22:07 UTC, oblitum commented
So, checking this again, clojure-lsp actually doesn't use whitespace as trigger characters for signature help.