[WIP] feat(handler): definition content on hover
neoclide/coc.nvim pull request #3243
Opened 2021-07-26 09:24 UTC by fannheyward

<img width="721" alt="截屏2021-07-26 下午5 16 07" src="https://user-images.githubusercontent.com/345274/126964992-5d6937a1-90ed-4554-b5c6-4e0ff9cd6e91.png">

VSCode: 

<img width="652" alt="截屏2021-07-26 下午5 18 38" src="https://user-images.githubusercontent.com/345274/126965316-38bd9ce3-9ca4-47bd-b192-78b53e12ca73.png">

cc @chemzqm , some Todos:

1. I put `definitionHover` in `handle` directly because we can use `locations` and `hover` to fetch and preview content, do we need to put into a new separate handle?
2. how to handle multiple definition locations? VSCode shows a `Click to show {0} definitions.` action, but we can't put action in hover by now
3. the definition content needs to be marked to markdown for highlighting

2021-07-26 10:59 UTC, chemzqm requested changes

2021-07-26 10:59 UTC, chemzqm commented on src/handler/index.ts
> +      await this.hover.previewHover(hovers, target)
Move the code block to `handler/hover.ts` and refactor `previewHover` to support `hovers: (Hover | Documentation)[]`

2021-07-26 10:59 UTC, chemzqm commented on src/handler/index.ts
> +    const locs = await this.locations.definitions()
This can't be used since we have to use `DefinitionLink` here,   you need refactor `DefinitionManager` module to export a method for get definition links, and make add new method to `languages` for provide definition links.

2021-07-26 11:04 UTC, chemzqm commented
> how to handle multiple definition locations? VSCode shows a Click to show {0} definitions. action, but we can't put action in hover by now

Show all of them should be fine.

2021-07-28 03:52 UTC, fannheyward commented on src/handler/index.ts
> +    const locs = await this.locations.definitions()
I'm a little confused, current `DefinitionManager` provides definitions as `Location`, you mean we should only use `DefinitionLink` for definition on hover? How about that LS doesn't return DefinitionLink?

2021-07-28 08:36 UTC, fannheyward commented on src/handler/index.ts
> +    const locs = await this.locations.definitions()
Will ignore if no definition links found.

2021-08-08 15:31 UTC, chemzqm commented
I've moved the code block to the end of buffer since syntax item with transparent could break syntax highlighting and I can't figure out how to fix it.

2021-08-08 15:32 UTC, merged