fix(hover): shift-left definition content
neoclide/coc.nvim pull request #3297
Opened 2021-08-19 06:57 UTC by fannheyward

Before:

<img width="703" alt="截屏2021-08-19 下午2 52 57" src="https://user-images.githubusercontent.com/345274/130021933-be0d1e9a-cc94-4e02-9d28-e29c94aafd07.png">

After:

<img width="698" alt="截屏2021-08-19 下午2 52 27" src="https://user-images.githubusercontent.com/345274/130021860-92bb5df8-b768-4fc3-8e3f-3f78bed4107f.png">

2021-08-19 12:26 UTC, chemzqm requested changes

2021-08-19 12:26 UTC, chemzqm commented on src/handler/hover.ts
> +          lines = lines.map(l => l.substring(lines[0].search(/\S/)))
It's possible to remove code that not indent and you should not call `lines[0].search` too many times.

2021-08-20 07:24 UTC, chemzqm requested changes

2021-08-20 07:24 UTC, chemzqm commented on src/handler/hover.ts
> +        const indent = lines[0].search(/\S/)
Bad regex, should check start position only

2021-08-20 07:24 UTC, chemzqm commented on src/handler/hover.ts
> +          lines = lines.map(l => l.search(/\S/) > 0 ? l.substring(indent) : l)
Use `line.startsWith` instead

2021-08-20 08:31 UTC, fannheyward commented on src/handler/hover.ts
> +          lines = lines.map(l => l.search(/\S/) > 0 ? l.substring(indent) : l)
Yes, we can use `line.startsWith` to check whether line indented with space/tab,  but I need the non-space position in first, to cut other lines. That's why I use `/\S/` to get the position. Do I miss-understand something you said?

2021-08-20 08:40 UTC, chemzqm requested changes

2021-08-20 08:40 UTC, chemzqm commented on src/handler/hover.ts
> +          lines = lines.map(l => l.search(/\S/) > 0 ? l.substring(indent) : l)
What if first line have four space indent but the line after have two space?

2021-08-20 08:40 UTC, chemzqm commented on src/handler/hover.ts
> +          lines = lines.map(l => l.search(/\S/) > 0 ? l.substring(indent) : l)
And the `search()` method could returns `-1` which you should ignore.
My suggestion is use `match` get indent text and check the line with `startsWith`

2021-08-20 08:47 UTC, fannheyward commented on src/handler/hover.ts
> +          lines = lines.map(l => l.search(/\S/) > 0 ? l.substring(indent) : l)
> use match get indent text

Got it.

2021-08-20 09:24 UTC, fannheyward commented on src/handler/hover.ts
> +          lines = lines.map(l => l.search(/\S/) > 0 ? l.substring(indent) : l)
@chemzqm  I found it's hard to use `match` to get the first line indent, so I use `line.length - line.trimStart().length` to get the indent.

2021-08-20 10:10 UTC, chemzqm commented
It still possible trim none space text of line, I'll make a fix.

2021-08-20 10:10 UTC, closed without merging