use nvim-treesitter's highlight group
neoclide/coc.nvim pull request #3355
Opened 2021-09-06 10:55 UTC by fannheyward

- https://github.com/neoclide/coc.nvim/issues/3345
- https://github.com/neoclide/coc.nvim/issues/3323

what've done:

1. use TS* hi group
2. add `coc.preferences.semanticTokensFiletypes` to enable semanticTokens for special language

2021-09-06 20:58 UTC, oblitum commented
Will this require to explicitly enable the languages for semantic tokens to work? My original suggestion was to have semantic tokens by default supported, but that when the user wants to, if it wants so, it could configure specific languages, or also, have it blacklisted for just a few.

2021-09-07 02:21 UTC, fannheyward commented
> Will this require to explicitly enable the languages for semantic tokens to work

I prefer to disable semanticTokens by default, because only clangd/rust-analzyer/gopls supports this by now, users can enable it by themself. Another reason is semanticTokens is not stable enough by now.

2021-09-07 11:04 UTC, oblitum commented
@fannheyward okay, I commented that because it could be annoying to have to list the languages, but I saw after that there's glob support.

2021-09-07 14:41 UTC, oblitum commented
At that, it should be documented in the added docs that glob pattern can be used to have it enabled for any server that supports it.

2021-09-08 03:52 UTC, fannheyward commented
>  be documented in the added docs that glob pattern

Done.

2021-09-08 04:05 UTC, oblitum commented on doc/coc.txt
>    tokens highlighting is disabled by default, you can enable it by add filetype
s/add filetype/adding a filetype/

2021-09-08 04:10 UTC, oblitum commented on data/schema.json
> +      "description": "Filetypes that enable semanticTokens highlighting",
"Filetypes that enable semanticTokens highlighting or [\"*\"] for any filetype"

2021-09-08 21:20 UTC, oblitum commented
Seems worth noticing that removing the simple default groups provided by `g:coc_default_semantic_highlight_groups` means to remove vim support for this kind of thing.

2021-09-09 01:28 UTC, fannheyward commented
>  means to remove vim support for this kind of thing

No, if the color scheme has TS* hi group defined for vim, for example https://github.com/sainnhe/sonokai/blob/61b796d94e7b0110f1bdf321cc1d19a841697a42/colors/sonokai.vim#L331, semanticTokens highlight supports vim too.

2021-09-09 01:29 UTC, oblitum commented
@fannheyward wow, seriously, that's really nice!

2021-10-17 03:21 UTC, oblitum commented
Glob pattern isn't working anymore, dunno what happened.

2021-11-27 22:29 UTC, darzok0914 commented
Hi, I'm currently using the CocSem_* highlight groups and I think they are great and a good complement of the TS* groups. Typically, C++ is quite hard to parse and understand for TreeSitter and clangd can provide more information. What I'm saying is that the highlight groups from Tree sitter and the one provided from lsp are not a perfect 1 to 1 mapping and we can have a better experience by combining them instead of trying to map them as it would result in a loss of information.

2021-12-15 08:48 UTC, fannheyward commented
cc @oblitum `tokenModifiers` has been handled, something like `TSDeprecated` will be highlighted.

2021-12-15 13:14 UTC, oblitum commented
> cc @oblitum `tokenModifiers` has been handled, something like `TSDeprecated` will be highlighted.

Nice. I tried it with Go (I had to `:hi link TSDeprecated CocDeprecatedHighlight` manually) but got the highlighting only at definition, never at call site:

![img-2021-12-15-101132](https://user-images.githubusercontent.com/1269815/146192563-15dbc4b1-d7a8-4d8f-9280-e70c0c152ef9.png)

All the function calls inside main are for deprecated functions.

> The problem is, hi group like `TSStatic/TSDeprecated/TSReadonly` are not defined by nvim-treesitter, we should provide these hi group, or user needed to define by themself.

Is it good idea to fallback highlighting (to `CocDeprecatedHighlight`) as commented in https://github.com/neoclide/coc.nvim/pull/3188#issuecomment-974490202?

2021-12-16 01:48 UTC, fannheyward commented
```go
package main

// Deprecated, use newFoof
func fooFunc() bool {
	return false
}

// Deprecated
const badPi = 3.141

func main() {
	fooFunc()
}
```

semanticTokens:

```
[
  { hlGroup: 'TSKeyword', lnum: 0, colStart: 0, colEnd: 7 },
  { hlGroup: 'TSNamespace', lnum: 0, colStart: 8, colEnd: 12 },
  { hlGroup: 'TSComment', lnum: 2, colStart: 0, colEnd: 26 },
  { hlGroup: 'TSKeyword', lnum: 3, colStart: 0, colEnd: 4 },
  { hlGroup: 'TSFunction', lnum: 3, colStart: 5, colEnd: 12 },
  { hlGroup: 'TSDefinition', lnum: 3, colStart: 5, colEnd: 12 },
  { hlGroup: 'TSDeprecated', lnum: 3, colStart: 5, colEnd: 12 },
  { hlGroup: 'TSType', lnum: 3, colStart: 15, colEnd: 19 },
  { hlGroup: 'TSDefaultLibrary', lnum: 3, colStart: 15, colEnd: 19 },
  { hlGroup: 'TSKeyword', lnum: 4, colStart: 1, colEnd: 7 },
  { hlGroup: 'TSVariable', lnum: 4, colStart: 8, colEnd: 13 },
  { hlGroup: 'TSReadonly', lnum: 4, colStart: 8, colEnd: 13 },
  { hlGroup: 'TSComment', lnum: 7, colStart: 0, colEnd: 13 },
  { hlGroup: 'TSKeyword', lnum: 8, colStart: 0, colEnd: 5 },
  { hlGroup: 'TSVariable', lnum: 8, colStart: 6, colEnd: 11 },
  { hlGroup: 'TSDefinition', lnum: 8, colStart: 6, colEnd: 11 },
  { hlGroup: 'TSReadonly', lnum: 8, colStart: 6, colEnd: 11 },
  { hlGroup: 'TSDeprecated', lnum: 8, colStart: 6, colEnd: 11 },
  { hlGroup: 'TSNumber', lnum: 8, colStart: 14, colEnd: 19 },
  { hlGroup: 'TSKeyword', lnum: 10, colStart: 0, colEnd: 4 },
  { hlGroup: 'TSFunction', lnum: 10, colStart: 5, colEnd: 9 },
  { hlGroup: 'TSDefinition', lnum: 10, colStart: 5, colEnd: 9 },
  { hlGroup: 'TSFunction', lnum: 11, colStart: 1, colEnd: 8 }
]
```

No `TSDeprecated` on call sites.

2021-12-16 02:01 UTC, oblitum commented
Hmm, okay, thanks for checking this, it's their then on that.

2022-01-11 13:59 UTC, jackhub commented
I am wondering does this will fix the problem I mentioned for clangd.
https://github.com/clangd/clangd/issues/985

2022-01-11 17:26 UTC, oblitum commented
@jackhub just give it a try with a tree-sitter colorscheme.

2022-01-11 20:32 UTC, oblitum commented
>  chemzqm force-pushed the feat/use-ts-hi-group branch from 788d4ee to 759cd81

😢 😕

2022-01-12 05:31 UTC, jackhub commented
> @jackhub just give it a try with a tree-sitter colorscheme.

I use the latest coc.nvim, how to configure it to have a try with tree sitter color scheme ?

2022-01-12 19:38 UTC, oblitum commented
@jackhub give it a try by pulling and building the branch of this pull request.

2022-01-13 05:39 UTC, jackhub commented
> @jackhub give it a try by pulling and building the branch of this pull request. [This is my configuration for neovim, for example](https://codeberg.org/oblitum/dotfiles/src/commit/b5161cbf6b17b03a3c1e678d45efaca9f9400817/.config/nvim/init.lua#L851-L852).

Cool, I have tested with this, it works.
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/4580635/149271717-24c49c95-1481-4113-91bf-2ce05212f78b.png">

I have a suggestion here. I want to highlight `DefaultLibaray` type, property, function, namespace different.
Here we just have a `TSDefaultLibaray` for types.

<img width="844" alt="image" src="https://user-images.githubusercontent.com/4580635/149272140-0c32a264-d2bb-498e-b7c0-90d0cc2e1695.png">
Like what Xcode does.

Thanks for your work.

2022-01-13 09:18 UTC, jackhub commented
> > @jackhub give it a try by pulling and building the branch of this pull request. [This is my configuration for neovim, for example](https://codeberg.org/oblitum/dotfiles/src/commit/b5161cbf6b17b03a3c1e678d45efaca9f9400817/.config/nvim/init.lua#L851-L852).
> 
> Cool, I have tested with this, it works. <img alt="image" width="1176" src="https://user-images.githubusercontent.com/4580635/149271717-24c49c95-1481-4113-91bf-2ce05212f78b.png">
> 
> I have a suggestion here. I want to highlight `DefaultLibaray` type, property, function, namespace differently. Here we just have a `TSDefaultLibaray` for types.
> 
> Also for declarations, I want to highlight different types of 'Declaration`. Like this, I want to keep macro declaration to be orange color. <img alt="image" width="529" src="https://user-images.githubusercontent.com/4580635/149277731-b6eee89c-563b-4451-aff8-2ba179af83d3.png">
> 
> Can we have to method to custom highlights for the all combination of token types and modifiers?
> 
> Maybe you can highlight all token types as default, ignore modifiers, users can define more precise highlight with modifier, like `TSTypeDeclaration`.
> 
> <img alt="image" width="583" src="https://user-images.githubusercontent.com/4580635/149275794-523847a4-a485-42fb-bdc1-5d8bed7d23f0.png">
> 
> Like what Xcode does.
> Thanks for your work.

I tried myself to deal with `DefaultLibrary` and `Declaration` modifiers, make it exactly same to Xcode highlight, but it's too customization, maybe coc.nvim can provide some better strategy for this.

`      var modifiers = legend.tokenModifiers.filter((_, m) => tokens[i + 4] & (1 << m)).map(m => SEMANTIC_HLGROUP_PREFIX + m)
      var group = SEMANTIC_HLGROUP_PREFIX + legend.tokenTypes[tokenType]
      if (modifiers.indexOf("TSDefaultLibrary") > -1) {
        if (legend.tokenTypes[tokenType] == "Class" ||
          legend.tokenTypes[tokenType] == "Interface" ||
          legend.tokenTypes[tokenType] == "Enum" ||
          legend.tokenTypes[tokenType] == "Type" ||
          legend.tokenTypes[tokenType] == "Namespace") {
          group = "TSTypeDefaultLibrary"
        } else {
          group = "TSOtherDefaultLibrary"
        }
        modifiers = []
      } else if (modifiers.indexOf("TSDeclaration") > -1) {
        if (legend.tokenTypes[tokenType] == "Class" ||
          legend.tokenTypes[tokenType] == "Interface" ||
          legend.tokenTypes[tokenType] == "Enum" ||
          legend.tokenTypes[tokenType] == "Type" ||
          legend.tokenTypes[tokenType] == "Namespace") {
          group = "TSTypeDeclaration"
          modifiers = []
        } else if (legend.tokenTypes[tokenType] == "Macro") {
        } else if (legend.tokenTypes[tokenType] == "Property" ||
          legend.tokenTypes[tokenType] == "Variable" ||
          legend.tokenTypes[tokenType] == "Parameter") {
          group = "TSVariable"
        } else {
          group = "TSOtherDeclaration"
        }
        modifiers = []
      } else {
        modifiers = []
      }
`
<img width="729" alt="image" src="https://user-images.githubusercontent.com/4580635/149301339-2faf9136-0227-4cd0-8680-9ba56cce9f0c.png">

2022-01-19 13:29 UTC, chemzqm requested changes

2022-01-19 13:29 UTC, chemzqm commented on data/schema.json
> +    "coc.preferences.semanticTokensFiletypes": {
My suggestion is use `semanticTokens.filetypes` instead and we will have more configuration for semantic highlights.

2022-01-19 13:29 UTC, chemzqm commented on doc/coc.txt
> -CocSem_*						*CocSem*
My suggestion is still use `CocSem` as prefix of highlight group and link to `TS` highlight groups when possible, so they're decoupled.

2022-01-20 19:39 UTC, oblitum commented
never mind, it's working, false alarm.

2022-01-20 20:06 UTC, chemzqm commented
Need create link to `TS*` highlight groups at https://github.com/neoclide/coc.nvim/blob/master/plugin/coc.vim#L438.

2022-01-21 03:21 UTC, fannheyward commented on doc/coc.txt
> -CocSem_*						*CocSem*
https://github.com/neoclide/coc.nvim/pull/3355/commits/c5251c2b3418a881eef757e131a76898ceeb43c0

I've linked `CocSem` to `TS` hi group, the problem is we can't provide all needed hi group. The first part is synced with https://github.com/microsoft/vscode-languageserver-node/blob/main/types/src/main.ts#L3480-L3531, the second part is came from nvim-treesitter's hi group, and LS will provide some more token/modifiers.

2022-01-21 18:14 UTC, chemzqm commented
@jackhub No need to hack the code any more, composed highlight group would work, checkout `:h CocSem`

2022-01-21 19:59 UTC, chemzqm approved these changes

2022-01-21 20:06 UTC, merged

2022-01-23 09:02 UTC, jackhub commented
> @jackhub No need to hack the code any more, composed highlight group would work, checkout `:h CocSem`

Thanks for your great works.

2022-01-25 11:16 UTC, daquexian commented
why semanticTokens.filetypes is empty by default? It should be `['*']` that aligns with the old coc.preferences.semanticTokensHighlights.

2022-01-25 12:16 UTC, chemzqm commented
Because we don't want to surprise users with changed highlights.

2022-01-25 16:13 UTC, damnskippy commented
Does the user have to explicitly call `CocAction('semanticHighlight')` to get the highlights, or does coc.nvim automatically make this call if `semanticTokens.filetypes`  is enabled for the current `&filetype` in vim.
In vim I see semantic highlighting working after calling `CocAction('semanticHighlight')`, but not automatically, so wanted to confirm if this is expected behavior.  Thanks.

2022-01-25 16:56 UTC, chemzqm commented
> does coc.nvim automatically make this call if semanticTokens.filetypes is enabled for the current &filetype in vim.

It should be automatic.

2022-01-25 17:44 UTC, damnskippy commented
Thanks for confirming, I'll look into my environment to see what's going on.