feat(commands): add `editor.action.formatDocument` command
neoclide/coc.nvim pull request #3699
Opened 2022-03-13 03:31 UTC by xiyaowong

2022-03-15 12:18 UTC, fannheyward commented
Why not add this to `src/commands.ts` with something like `await plugin.cocAction('format')`?

2022-03-16 16:48 UTC, chemzqm requested changes

2022-03-16 16:48 UTC, chemzqm commented on src/handler/format.ts
> +    handler.addDisposable(commandManager.registerCommand('editor.action.formatDocument', async (bufnr?: number) => {
It's better to use `uri` instead of `bufnr`.

2022-03-17 00:42 UTC, xiyaowong commented on src/handler/format.ts
> +    handler.addDisposable(commandManager.registerCommand('editor.action.formatDocument', async (bufnr?: number) => {
Why? Users are more likely to provide bufnr, same as organizeImport, although the most of users may not know that arguments can be provided

2022-03-17 09:55 UTC, chemzqm commented on src/handler/format.ts
> +    handler.addDisposable(commandManager.registerCommand('editor.action.formatDocument', async (bufnr?: number) => {
Because one `bufnr` could be used for different document, try `:tabe | echo bufnr('%')` and then open another file, you can see they share same bufnr.

2022-03-17 10:11 UTC, xiyaowong commented on src/handler/format.ts
> +    handler.addDisposable(commandManager.registerCommand('editor.action.formatDocument', async (bufnr?: number) => {
I don't understand. And following your steps, `bufnr` has not been the same.

2022-03-17 10:17 UTC, kevinhwang91 commented on src/handler/format.ts
> +    handler.addDisposable(commandManager.registerCommand('editor.action.formatDocument', async (bufnr?: number) => {
IMO, coc.nvim is LSP-related framework, users should translate bufnr to uri. Please run `:h uri_from_bufnr` In Neovim.

2022-03-17 10:28 UTC, xiyaowong commented on src/handler/format.ts
> +    handler.addDisposable(commandManager.registerCommand('editor.action.formatDocument', async (bufnr?: number) => {
thx, I have known this section. Just don't understand many other methods are used bufnr, this is a historical legacy or other considerations?

2022-03-17 10:29 UTC, chemzqm commented on src/handler/format.ts
> +    handler.addDisposable(commandManager.registerCommand('editor.action.formatDocument', async (bufnr?: number) => {
The buffer could be not attached for some reasons `:h CocAction('ensureDocument')`, using `uri` would be safer.

2022-03-17 10:31 UTC, chemzqm commented on src/handler/format.ts
> +    handler.addDisposable(commandManager.registerCommand('editor.action.formatDocument', async (bufnr?: number) => {
You can use `bufnr` or `uri`, `bufnr` is for vim staff and `uri` for LSP related.

2022-03-17 11:32 UTC, merged