Update `CocSem*` Highlight Links
neoclide/coc.nvim pull request #4384
Opened 2022-11-22 17:29 UTC by LebJe

Link `CocSem*` to `@*` [because nvim-treesitter removed `TS*`](https://github.com/nvim-treesitter/nvim-treesitter/pull/3656).

Highlights like `@file`, `@package` `@array` don't exist, but color schemes can add highlights for them.

2022-11-25 13:12 UTC, oxalica requested changes

2022-11-25 13:12 UTC, oxalica commented on plugin/coc.vim
> +        \ 'Struct': ['@type', 'Identifier'],
```suggestion
        \ 'Struct': ['@structure', 'Identifier']
```

Also `Enum`, `Interface`, `EnumMember` and etc used to have different TS* hl names, while how they are merged into same `@type` or `@property`. Is this intended?

2022-11-25 16:17 UTC, LebJe commented on plugin/coc.vim
> +        \ 'Struct': ['@type', 'Identifier'],
When colorschemes updated ([1](https://github.com/navarasu/onedark.nvim/pull/110/files), [2](https://github.com/ellisonleao/gruvbox.nvim/pull/163)), they did not add `Enum`, `Interface`, `structure`, or `EnumMember` highlights. Also, none of those highlights are mentioned in [nvim-treesitter’s CONTRIBUTING.md ](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights).

2022-11-26 14:02 UTC, oxalica commented on plugin/coc.vim
> +        \ 'Struct': ['@type', 'Identifier'],
But unlike others, `@structure` is a thing shipped with neovim 0.8.1, which links to `Structure` by default.
See `:help treesitter-highlight`.

2022-11-28 10:00 UTC, oxalica approved these changes

2022-11-30 08:48 UTC, fannheyward commented
The `@*` hi groups only available in nvim 0.8+, this means change `TS*` to `@*` drops nvim 0.7 supports. Do we need to support both? cc @chemzqm 

I prefer to drop the support because:

1. users always use nvim latest release
2. `CocSem*` will fallback to `String` etc if treesitter not available

2022-12-02 18:59 UTC, chemzqm commented
> I prefer to drop the support because:
> 
> 1. users always use nvim latest release
> 2. `CocSem*` will fallback to `String` etc if treesitter not available

Agreed, don't think we need support old version TS highlights.

2022-12-07 11:24 UTC, fannheyward commented
cc @chemzqm, do you still have any questions on this change?

2022-12-07 18:03 UTC, merged

2022-12-07 18:03 UTC, chemzqm commented
@all-contributors please add @LebJe for code.