feat(diagnostic): add `showRelatedInformation`
neoclide/coc.nvim pull request #5090
Opened 2024-07-18 09:26 UTC by hexh250786313

See: https://github.com/neoclide/coc.nvim/issues/5086

2024-07-18 09:47 UTC, fannheyward commented
screenshot please, for better understanding.

2024-07-18 10:14 UTC, hexh250786313 commented
@fannheyward Screenshots added.

2024-07-18 10:24 UTC, fannheyward commented
Shall we remove the `separateRelatedInformationAsDiagnostics`? This new configuration controls to display related in floating window, I'd prefer to remove the old configuration, which only separates them but doesn't shows in relation.

2024-07-19 02:34 UTC, hexh250786313 commented
@fannheyward Removing the `separateRelatedInformationAsDiagnostics` feature is ok, the separated diagnostic doesn't really provide much useful information:

![image](https://github.com/user-attachments/assets/136a9296-852c-4909-889a-9fbbcd328531)

If we need to find the related diagnostic, we can just use `:CocCommand workspace.diagnosticRelated`.

Moreover, for some reason, the `separateRelatedInformationAsDiagnostics` only works for customized language services configured by `coc-settings.json`, not for some of plug-in language servers (e.g. coc-tsserver). See: https://github.com/neoclide/coc.nvim/discussions/5078

I will make a commit for it shortly.

2024-07-19 02:46 UTC, fannheyward commented
> the separated diagnostic doesn't really provide much useful informatio

Yes, this is what I said not showing in relation.

2024-07-22 02:38 UTC, fannheyward requested changes

2024-07-22 02:38 UTC, fannheyward commented on src/language-client/client.ts
>      // TODO make is async
remove this comment too.

2024-07-22 03:45 UTC, hexh250786313 commented on src/language-client/client.ts
>      // TODO make is async
Done.

2024-07-22 03:55 UTC, fannheyward approved these changes

2024-07-22 04:23 UTC, merged