fix(inlayHint&semanticTokens): Fix range send to server
neoclide/coc.nvim pull request #5192
Opened 2024-11-19 10:19 UTC by tcx4c70

From LSP spec [1]:
> .. the end position is exclusive. If you want to specify a range that
> contains a line including the line ending character(s) then use an end
> position denoting the start of the next line.

but it doesn't mention what we should send to server if the file hasn't EOL. VS Code will set end = { line = last line number (0-based), character = length of the last line}. This fix will change the behavior to the same as VS Code so that some language servers (such as roslyn language server) will work normally.

[1] https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#range

2024-11-19 12:03 UTC, fannheyward requested changes

2024-11-19 12:03 UTC, fannheyward commented on src/model/textdocument.ts
> +      start = Position.create(start.line, Math.max(start.line, range.start.character))
`Math.max(start.character, range.start.character)`

2024-11-19 12:12 UTC, fannheyward requested changes

2024-11-19 12:12 UTC, fannheyward commented on src/model/textdocument.ts
> +      end = Position.create(end.line, Math.min(end.character, range.end.character))
Why `Math.min`? I can't get this.

2024-11-19 13:13 UTC, tcx4c70 commented on src/model/textdocument.ts
> +      start = Position.create(start.line, Math.max(start.line, range.start.character))
Oops, will the typo

2024-11-20 02:45 UTC, fannheyward approved these changes

2024-11-20 02:45 UTC, merged